# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a49f0138a6f0453f5f5a74ca29b6085a6823e063d4e11229cbd7dd01bbc7076447e2e6dfb561a9a4ab944fd176bbf8962086a671cc3557b85ac0a4494c82ac9

test:
  secret_key_base: 8f88d5837760ca339354b85486882fa597025fa8b8015a74dc949fb300018e642a797ab1dcdf6f62fb0182d02b46d653d9506eac6df087edabfc3f76ce280f53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
